# Generated by Django 5.2.4 on 2025-07-12 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_manager",
                    models.BooleanField(
                        default=False, help_text="Designates if this user is a manager"
                    ),
                ),
                (
                    "is_normal_user",
                    models.BooleanField(
                        default=True,
                        help_text="Designates if this user is a normal user",
                    ),
                ),
                (
                    "dir_name",
                    models.CharField(
                        help_text="Directory name assigned to this user",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal User"),
                            ("manager", "Manager"),
                            ("superuser", "Superuser"),
                        ],
                        default="normal",
                        help_text="Type of user (normal, manager, superuser)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "auth_user_profile",
            },
        ),
    ]
